#####
#  note - all pages use Windows-1252 encoding and NOT UTF-8 !!!!
#####

2011: tablesb/braz2011.html  !! Windows-1252
2012: tablesb/braz2012.html  !! Windows-1252
2013: tablesb/braz2013.html  !! Windows-1252
2014: tablesb/braz2014.html  !! Windows-1252
2015: tablesb/braz2015.html  !! Windows-1252
2016: tablesb/braz2016.html  !! Windows-1252
2017: tablesb/braz2017.html  !! Windows-1252
2018: tablesb/braz2018.html  !! Windows-1252
2019: tablesb/braz2019.html  !! Windows-1252
2020: tablesb/braz2020.html  !! Windows-1252   ## 2020/21  - extended for corona
2021: tablesb/braz2021.html  !! Windows-1252
2022: tablesb/braz2022.html  !! Windows-1252
2023: tablesb/braz2023.html  !! Windows-1252
2024: tablesb/braz2024.html  !! Windows-1252
